---
application:
  name: "cao-sem-casa-backend"
  project: "cao-sem-casa-api"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "db_adocao_animais"
  version: "12"
routers:
- name: "main-cao-sem-casa-backend"
  routes:
  - application_name: "cao-sem-casa-backend"
    paths:
    - "/*"
